[package]
name = "common"
version = "0.1.0"
authors = ["Paweł Romanowski <pawroman@gmail.com>"]
edition = "2018"

[lib]
# disable doctest because of failure_derive import problems
doctest = false

[dependencies]
failure = "0.1.3"

[dev-dependencies]
tempfile = "3.0.5"
